services:
    litebasedb-function:
        build:
            context: .
        environment:
            APP_ENV: ${APP_ENV}
            APP_HOST: ${APP_HOST}
            AWS_LAMBDA_FUNCTION_NAME: ${AWS_LAMBDA_FUNCTION_NAME}
            AWS_LAMBDA_FUNCTION_MEMORY_SIZE: 128
            AWS_LAMBDA_FUNCTION_TIMEOUT: 900
            LITEBASEDB_CACHE_PATH: "/tmp/litebasedb-cache"
            LITEBASEDB_DATA_PATH: "/mnt/data"
            LITEBASEDB_TMP_PATH: "/tmp"
            LITEBASEDB_DB_UUID: ${LITEBASEDB_DB_UUID}
            LITEBASEDB_PORT: 80
            LITEBASEDB_ENCRYPTION_KEY: ${LITEBASEDB_ENCRYPTION_KEY}
            LITEBASEDB_REGION: ${LITEBASEDB_REGION}
        ports:
            - "8001:8080"
        volumes:
            - .:/var/task
            # - ./data:/mnt/data
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    data:
