package auth

const (
	DatabasePrivilegeAnalyze           Privilege = "database:analyze"
	DatabasePrivilegeAttach            Privilege = "database:attach"
	DatabasePrivilegeAlterTable        Privilege = "database:alter_table"
	DatabasePrivilegeCreateIndex       Privilege = "database:create_index"
	DatabasePrivilegeCreateTable       Privilege = "database:create_table"
	DatabasePrivilegeCreateTempTable   Privilege = "database:create_temp_table"
	DatabasePrivilegeCreateTempTrigger Privilege = "database:create_temp_trigger"
	DatabasePrivilegeCreateTempView    Privilege = "database:create_temp_view"
	DatabasePrivilegeCreateTrigger     Privilege = "database:create_trigger"
	DatabasePrivilegeCreateView        Privilege = "database:create_view"
	DatabasePrivilegeCreateVTable      Privilege = "database:create_vtable"
	DatabasePrivilegeDelete            Privilege = "database:delete"
	DatabasePrivilegeDetach            Privilege = "database:detach"
	DatabasePrivilegeDropIndex         Privilege = "database:drop_index"
	DatabasePrivilegeDropTable         Privilege = "database:drop_table"
	DatabasePrivilegeDropTrigger       Privilege = "database:drop_trigger"
	DatabasePrivilegeDropView          Privilege = "database:drop_view"
	DatabasePrivilegeFunction          Privilege = "database:function"
	DatabasePrivilegeInsert            Privilege = "database:insert"
	DatabasePrivilegePragma            Privilege = "database:pragma"
	DatabasePrivilegeRead              Privilege = "database:read"
	DatabasePrivilegeRecursive         Privilege = "database:recursive"
	DatabasePrivilegeReindex           Privilege = "database:reindex"
	DatabasePrivilegeSavepoint         Privilege = "database:savepoint"
	DatabasePrivilegeSelect            Privilege = "database:select"
	DatabasePrivilegeTransaction       Privilege = "database:transaction"
	DatabasePrivilegeUpdate            Privilege = "database:update"

	DatabasePrivilegeBackup  Privilege = "database:backup"
	DatabasePrivilegeRestore Privilege = "database:restore"
)
