package sqlite3

/*
#include <../../dist/sqlite3.h>
*/
import "C"

const (
	SQLITE_ABORT          = C.SQLITE_ABORT
	SQLITE_AUTH           = C.SQLITE_AUTH
	SQLITE_BUSY           = C.SQLITE_BUSY
	SQLITE_CANTOPEN       = C.SQLITE_CANTOPEN
	SQLITE_CONSTRAINT     = C.SQLITE_CONSTRAINT
	SQLITE_CORRUPT        = C.SQLITE_CORRUPT
	SQLITE_DONE           = C.SQLITE_DONE
	SQLITE_EMPTY          = C.SQLITE_EMPTY
	SQLITE_ERROR          = C.SQLITE_ERROR
	SQLITE_FORMAT         = C.SQLITE_FORMAT
	SQLITE_FULL           = C.SQLITE_FULL
	SQLITE_INTERNAL       = C.SQLITE_INTERNAL
	SQLITE_INTERRUPT      = C.SQLITE_INTERRUPT
	SQLITE_IOERR          = C.SQLITE_IOERR
	SQLITE_LOCKED         = C.SQLITE_LOCKED
	SQLITE_MISMATCH       = C.SQLITE_MISMATCH
	SQLITE_MISUSE         = C.SQLITE_MISUSE
	SQLITE_NOLFS          = C.SQLITE_NOLFS
	SQLITE_NOMEM          = C.SQLITE_NOMEM
	SQLITE_NOTADB         = C.SQLITE_NOTADB
	SQLITE_NOTFOUND       = C.SQLITE_NOTFOUND
	SQLITE_NOTICE         = C.SQLITE_NOTICE
	SQLITE_OK             = C.SQLITE_OK
	SQLITE_PERM           = C.SQLITE_PERM
	SQLITE_PROTOCOL       = C.SQLITE_PROTOCOL
	SQLITE_RANGE          = C.SQLITE_RANGE
	SQLITE_READONLY       = C.SQLITE_READONLY
	SQLITE_ROW            = C.SQLITE_ROW
	SQLITE_SCHEMA         = C.SQLITE_SCHEMA
	SQLITE_TOOBIG         = C.SQLITE_TOOBIG
	SQLITE_WARNING        = C.SQLITE_WARNING
	SQLITE_OPEN_READONLY  = C.SQLITE_OPEN_READONLY
	SQLITE_OPEN_READWRITE = C.SQLITE_OPEN_READWRITE
	SQLITE_OPEN_CREATE    = C.SQLITE_OPEN_CREATE
	SQLITE_OPEN_URI       = C.SQLITE_OPEN_URI
	SQLITE_OPEN_MEMORY    = C.SQLITE_OPEN_MEMORY

	SQLITE_DENY                = C.SQLITE_DENY
	SQLITE_IGNORE              = C.SQLITE_IGNORE
	SQLITE_CREATE_INDEX        = C.SQLITE_CREATE_INDEX
	SQLITE_CREATE_TABLE        = C.SQLITE_CREATE_TABLE
	SQLITE_CREATE_TEMP_INDEX   = C.SQLITE_CREATE_TEMP_INDEX
	SQLITE_CREATE_TEMP_TABLE   = C.SQLITE_CREATE_TEMP_TABLE
	SQLITE_CREATE_TEMP_TRIGGER = C.SQLITE_CREATE_TEMP_TRIGGER
	SQLITE_CREATE_TEMP_VIEW    = C.SQLITE_CREATE_TEMP_VIEW
	SQLITE_CREATE_TRIGGER      = C.SQLITE_CREATE_TRIGGER
	SQLITE_CREATE_VIEW         = C.SQLITE_CREATE_VIEW
	SQLITE_DELETE              = C.SQLITE_DELETE
	SQLITE_DROP_INDEX          = C.SQLITE_DROP_INDEX
	SQLITE_DROP_TABLE          = C.SQLITE_DROP_TABLE
	SQLITE_DROP_TEMP_INDEX     = C.SQLITE_DROP_TEMP_INDEX
	SQLITE_DROP_TEMP_TABLE     = C.SQLITE_DROP_TEMP_TABLE
	SQLITE_DROP_TEMP_TRIGGER   = C.SQLITE_DROP_TEMP_TRIGGER
	SQLITE_DROP_TEMP_VIEW      = C.SQLITE_DROP_TEMP_VIEW
	SQLITE_DROP_TRIGGER        = C.SQLITE_DROP_TRIGGER
	SQLITE_DROP_VIEW           = C.SQLITE_DROP_VIEW
	SQLITE_INSERT              = C.SQLITE_INSERT
	SQLITE_PRAGMA              = C.SQLITE_PRAGMA
	SQLITE_READ                = C.SQLITE_READ
	SQLITE_SELECT              = C.SQLITE_SELECT
	SQLITE_TRANSACTION         = C.SQLITE_TRANSACTION
	SQLITE_UPDATE              = C.SQLITE_UPDATE
	SQLITE_ATTACH              = C.SQLITE_ATTACH
	SQLITE_DETACH              = C.SQLITE_DETACH
	SQLITE_ALTER_TABLE         = C.SQLITE_ALTER_TABLE
	SQLITE_REINDEX             = C.SQLITE_REINDEX
	SQLITE_ANALYZE             = C.SQLITE_ANALYZE
	SQLITE_CREATE_VTABLE       = C.SQLITE_CREATE_VTABLE
	SQLITE_DROP_VTABLE         = C.SQLITE_DROP_VTABLE
	SQLITE_FUNCTION            = C.SQLITE_FUNCTION
	SQLITE_SAVEPOINT           = C.SQLITE_SAVEPOINT
	SQLITE_COPY                = C.SQLITE_COPY
	SQLITE_RECURSIVE           = C.SQLITE_RECURSIVE
)
