name: Continuos Delivery

on:
  release:
    types: [published]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Run tests
        run: go test runtime

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          # mask-aws-account-id: false

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Build the code
        run: GOOS=linux GOARCH=arm64 go build ./function -o bootstrap

      - name: Zip the code
        id: package
        run: |
          zip -r ${{ github.sha }}.zip bootstrap
          echo ::set-output name=zip::${{ github.sha }}.zip

      - name: Upload the code
        id: upload
        run: |
          aws s3 cp ./${{ steps.package.outputs.zip }} s3://${{ secrets.AWS_S3_BUCKET_NAME }}/${{ github.sha }}.zip

      - name: Output layer version
        run: |
          echo "### Published Lambda Code:" >> $GITHUB_STEP_SUMMARY
          echo "Lambda Code:" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.package.outputs.zip }} >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
