name: Continuous Integration

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '**/*.md'
    tags-ignore:
      - '**'
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          [
            { name: 'auth', path: pkg/auth },
            { name: 'backups', path: pkg/backups },
            { name: 'cache', path: pkg/cache },
            { name: 'cluster', path: pkg/cluster },
            { name: 'database', path: pkg/database },
            { name: 'http', path: pkg/http },
            { name: 'logs', path: pkg/logs },
            { name: 'sqlite3', path: pkg/sqlite3 },
            { name: 'vfs', path: pkg/vfs },
          ]
    defaults:
      run:
        working-directory: ${{ matrix.package.path }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache-dependency-path: go.sum

      - name: Run tests
        env:
          LITEBASE_TEST_DATA_PATH: /tmp/litebase-test-${{ github.run_id }}-${{ matrix.package.name }}
          LITEBASE_ROOT_DIRECTORY: ${{ github.workspace }}/
        run: |
          go test . -v

      - name: Cleanup test data
        if: always()
        run: |
          rm -rf /tmp/litebase-test-${{ github.run_id }}-${{ matrix.package.name }} || true
