name: Continuous Integration

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '**/*.md'
    tags-ignore:
      - '**'
  pull_request:
    branches: [main, develop]

jobs:
  setup-and-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Download Go modules
        run: go mod download

  test:
    needs: setup-and-cache
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          [
            { name: 'auth', path: pkg/auth },
            { name: 'backups', path: pkg/backups },
            { name: 'cache', path: pkg/cache },
            { name: 'cluster', path: pkg/cluster },
            { name: 'database', path: pkg/database },
            { name: 'http', path: pkg/http },
            { name: 'logs', path: pkg/logs },
            { name: 'sqlite3', path: pkg/sqlite3 },
            { name: 'vfs', path: pkg/vfs },
          ]
    defaults:
      run:
        working-directory: ${{ matrix.package.path }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache-dependency-path: go.sum

      - name: Run tests
        run: |
          go test . -v

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: TestResults-${{ matrix.package.name }}
          path: TestResults-${{ matrix.package.name }}.json
