name: Continuous Integration

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '.github/workflows/cd.yml'
    tags-ignore:
      - '**'
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - uses: actions/checkout@v3

      - name: Run tests
        run: go test runtime
